import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* grid layout with fixed navbar at the top */}
        <div className="grid h-screen grid-cols-1 grid-rows-[auto_1fr]">
          <Header />
          <main className="overflow-y-auto max-w-7xl p-8 mx-auto w-full">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
