import Image from "next/image";

export default function Home() {
  return (
    <main className="">
      <div>Ostia</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
      <div>empty</div>
    </main>
  );
}
